FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8501

HEALTHCHECK CMD curl --fail http://localhost:8581/_stcore/health || exit 1

CMD ["streamlit", "run", "app.py", "--server.port=8581", "--server.adress=0.0.0.0"]